use_frameworks!

platform :ios, '13.0'

target 'cie-sdk-ios_Example' do
  #pod 'cie-sdk-ios', :path => '../'

  spm_pkg "IOWalletCIE", :url => "git@github.com:pagopa/cie-sdk-ios.git", :branch => "feature/refactoring"

  target 'cie-sdk-ios_Tests' do
    inherit! :search_paths

    
  end
end
