

platform :ios, '13.0'

target 'cie-sdk-ios_Example' do
  use_frameworks!
  #pod 'cie-sdk-ios', :path => '../'

  spm_pkg "CieSDK", :relative_path => "../../../cie-sdk-ios/"

  target 'cie-sdk-ios_Tests' do
    inherit! :search_paths

    
  end
end
